Document: info6005cw1er2g11
Title: Debian info6005cw1er2g11 Manual
Author: <insert document author here>
Abstract: This manual describes what info6005cw1er2g11 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/info6005cw1er2g11/info6005cw1er2g11.sgml.gz

Format: postscript
Files: /usr/share/doc/info6005cw1er2g11/info6005cw1er2g11.ps.gz

Format: text
Files: /usr/share/doc/info6005cw1er2g11/info6005cw1er2g11.text.gz

Format: HTML
Index: /usr/share/doc/info6005cw1er2g11/html/index.html
Files: /usr/share/doc/info6005cw1er2g11/html/*.html
